const ACTION_TYPE = {
  ADD_SECTION: "ADD_SECTION",
  INPUT_SECTION_NAME: "INPUT_SECTION_NAME",
  ADD_CARD: "ADD_CARD",
  DELETE_CARD: "DELETE_CARD",
  INPUT_TASK_CARD_NAME: "INPUT_TASK_CARD_NAME",
  DRAG_HAPPENED: "DRAG_HAPPENED",
} as const;

export default ACTION_TYPE;
